---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: istio-system
spec:
  values:
    global:
      azure:
        tenant: 9f784c1c-28b2-4cef-8ac3-c503e04c906a
        appid: 5002b947-492a-42c4-88db-cd3777cc8688
